### ISSUE TITLE
no results after startup

### ISSUE THREAD

**Issue by Sombreroz** [derjasper/TankenApp#9] opened 2016-01-15 13:47 UTC
If I start the App on bq E 4.5 OTA 8.5 there are no gas stations displayed ("keine Ergebnisse"). Pressing the reload button does not help. 
Only if I go on filter settings and back again the gas stations are displayed.

**Comment by derjasper** [comment] 2016-01-26 17:56
fix is in the store

**Comment by Sombreroz** [comment] 2016-01-26 18:23
Thank you very much!

**Comment by Sombreroz** [comment] 2016-01-26 19:04
I have just tested it on E 4.5:
At the first run after the update I had to choose the data source. After  
selecting "Tankerkönig" the App worked normally. Even bug #10 was gone.
Then I closed the App and restarted it. This time bug#9 was present again  
saying "keine Internetverbindung" with no results. Switching to Filters  
and back again cured it like before.

So essentially bug #9 is not solved.

best regards
U. Schicke

**Comment by Sombreroz** [comment] 2016-01-26 21:04
Update:
Tapping on "refresh" displays the results without bug#10. So there is an  
improvement!
About bug#10: it only happens after going to Filters and back! Maybe that  
can help to fix it..

I have just tested it on E 4.5:
At the first run after the update I had to choose the data source. After  
selecting "Tankerkönig" the App worked normally. Even bug #10 was gone.
Then I closed the App and restarted it. This time bug#9 was present again  
saying "keine Internetverbindung" with no results. Switching to Filters  
and back again cured it like before.

So essentially bug #9 is not solved.

best regards
U. Schicke

**Comment by derjasper** [comment] 2016-01-26 21:35
Strange, so I will wait until the emulator is fixed, then I will be able to reproduce this bug

**Comment by derjasper** [comment] 2016-08-27 15:40
Is this issue fixed in the latest version?

**Comment by Sombreroz** [comment] 2016-08-27 15:55
The latest version does not start anymore. Just splash screen for 0,5  
seconds.
BQ e4.5

**Comment by derjasper** [comment] 2016-08-27 16:13
Okay, don't know why it crashes, perhaps it's using APIs that are not available on Ubuntu Phone yet. I unpublished the version, you may reinstall the app to get the old version.

**Comment by derjasper** [comment] 2016-08-27 20:33
Ok, another version has been released. Does it install and fix this bug?

**Comment by Sombreroz** [comment] 2016-08-28 06:00
It installs and works faster than the old version!
But it starts up with "Keine Egebnisse gefunden. Bitte überprüfe deine  
Internetverbindung.......
After a refresh (circle symbol) it displays the results correctly but the  
upmost results line is still halfway hidden under under the status line.  
This can be corrected by pulling down the screen.
Can I send you screenshots by telegram?

**Comment by derjasper** [comment] 2016-08-28 08:32
Please send them to jasper@bluetreehouse.de

**Comment by derjasper** [comment] 2016-09-04 12:49
#10 is maybe a bug in Ubuntu.

Please try to completely remove TankenApp from your phone, including user data (delete the ~/.config/com.ubuntu.developer.derjasper.tankenapp folder) and reinstall it.

**Comment by derjasper** [comment] 2018-02-04 10:20
Closed due to inactivity and unreproducibility

**Closed as completed by derjasper** 2018-02-04 10:20 UTC
Labels: bug, invalid
